# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
    - mkdir .public
    - unzip code/html.zip
    - ls 
    - cp -r html/* .public
    - mv .public public
  artifacts:
    paths:
      - public

